### PR TITLE
don't include C++ headers in C

### PR DESCRIPTION
**Pull request by CapsAdmin**

### CODE REVIEW

**Comment by CapsAdmin** [comment]
I forgot some namespace stuff as well and messed up the history. Feel free to just do it yourself and close this.

**Comment by panzi** [comment]
It also looks like there is an `#endif` to many.

**Comment by CapsAdmin** [comment]
yeah it messed up in merge. can you do it?

**Comment by panzi** [comment]
Right now I don't have the head for it.

**Comment by CapsAdmin** [comment]
I'll make a new pull request. I don't have the head for messing with git like this either lol

**Pull request closed without merging**
